### PR TITLE
Gamedev

### PR DESCRIPTION
**Pull request by shahsyedzafar**
#Game functionality

* Score update and flashing 
* logic for creating new patient in agent part
* Agent request algorithm

### CODE REVIEW

**Comment by super9user** [comment]
Are we planning to show this for Wednesday's demo?
If yes, has this been tested? (Because there seem to be tons of changes here, many of which are hard to understand. Making the code review difficult.)

**Comment by super9user** [comment]
I ask this question only because of Wednesday's demo.

**Review by shahsyedzafar — COMMENTED** [review]
LGTM. Changes are mostly in game implementation files which are fine

**Comment by shahsyedzafar** [comment]
@super9user Yes, it is important for Wednesday as per the vision document. I pulled code from master and issued a pull request.

**Comment by shahsyedzafar** [comment]
@adityab17190 and @yousuf031991 . Let us know if your changes are fine in this pull request.

**Pull request merged**
